# Generated by Django 5.0.6 on 2024-07-06 16:57

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('thumb', models.ImageField(default='thumbs/default.jpg', upload_to='thumbs')),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('a', 'Archived'), ('pa', 'Pending Approval'), ('d', 'Deleted')], default='p', max_length=2)),
                ('content', ckeditor.fields.RichTextField(default='')),
                ('category', models.ManyToManyField(related_name='posts', to='blog.category')),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
    ]
