# Generated by Django 5.0.6 on 2024-07-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
