# Generated by Django 5.0.6 on 2024-07-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_rename_category_post_categories_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_status',
            field=models.CharField(choices=[('o', 'Open'), ('c', 'Close')], default='o', max_length=1),
        ),
    ]
