# Generated by Django 5.0.6 on 2024-07-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
