# Generated by Django 5.0.6 on 2024-06-14 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('publication_link', models.URLField(blank=True)),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('conference', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='resume.publication')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('gpa_base', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('thesis', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('DIP', 'Diploma'), ('BD', 'B.Sc.'), ('MD', 'M.Sc.'), ('PHD', 'Ph.D.'), ('POSTDOC', 'Postdoctoral')], default='DIP', max_length=8)),
                ('advisors', models.ManyToManyField(related_name='educations', to='resume.advisor')),
                ('university', models.ManyToManyField(related_name='educations', to='resume.university')),
            ],
        ),
    ]
