# Generated by Django 5.0.6 on 2024-06-14 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='thesis',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='education',
            name='university',
        ),
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='educations', to='resume.university'),
        ),
    ]
