# Generated by Django 5.0.6 on 2024-06-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_education_gpa_alter_education_gpa_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree_rank',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='education',
            name='thesis_score',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='education',
            name='advisors',
            field=models.ManyToManyField(blank=True, related_name='educations', to='resume.advisor'),
        ),
    ]
