# Generated by Django 5.0.6 on 2024-06-30 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_education_degree_rank_education_thesis_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(help_text='Enter a valid hex color code (e.g., #FFFFFF).', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FFFFFF).', regex='^#[0-9A-Fa-f]{6}$')])),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_link',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.AddField(
            model_name='publicationlink',
            name='type',
            field=models.ManyToManyField(related_name='links', to='resume.linktype'),
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(related_name='publication', to='resume.author'),
        ),
    ]
