# Generated by Django 5.0.6 on 2024-07-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_achievements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Achievements',
        ),
    ]
