# Generated by Django 5.0.6 on 2024-07-02 14:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_achievement_delete_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='bio',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
