# Generated by Django 5.0.6 on 2024-07-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_institution_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
