# Generated by Django 5.0.6 on 2024-07-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_bio_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
    ]
