# Generated by Django 5.0.6 on 2024-07-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_alter_university_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='institution',
            new_name='institutions',
        ),
    ]
