# Generated by Django 5.0.6 on 2024-07-04 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_skillcategory_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='university',
        ),
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='educations', to='resume.institution'),
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
