# Generated by Django 5.0.6 on 2024-07-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name_plural': 'Skill Categories'},
        ),
    ]
