# Generated by Django 5.0.6 on 2024-07-04 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_alter_skillcategory_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='start',
            new_name='start_date',
        ),
    ]
